### ISSUE TITLE
"Maximum call stack size exceeded" working with large MultiPolygon's

### ISSUE THREAD

**Issue by contra** [mapbox/geojsonhint#43]
```
/Users/contra/Projects/staeco/node_modules/geojsonhint/object.js:151
                coords.forEach(function(c) {
                       ^

RangeError: Maximum call stack size exceeded
    at Array.forEach (native)
    at positionArray (/Users/contra/Projects/staeco/node_modules/geojsonhint/object.js:151:24)
    at /Users/contra/Projects/staeco/node_modules/geojsonhint/object.js:152:21
    at Array.forEach (native)
    at positionArray (/Users/contra/Projects/staeco/node_modules/geojsonhint/object.js:151:24)
    at Object.MultiPolygon (/Users/contra/Projects/staeco/node_modules/geojsonhint/object.js:224:13)
    at root (/Users/contra/Projects/staeco/node_modules/geojsonhint/object.js:35:26)
    at Object.hint (/Users/contra/Projects/staeco/node_modules/geojsonhint/object.js:319:5)
    at Object.hint (/Users/contra/Projects/staeco/node_modules/geojsonhint/index.js:38:46)
    at Object.normalizeGeoJsonGeometry (/Users/contra/Projects/staeco/node_modules/knex-postgis/lib/utils.js:8:28)
    at Formatter.wrapGeoJSON (/Users/contra/Projects/staeco/node_modules/knex-postgis/lib/index.js:58:18)
    at Object.postgis.geomFromGeoJSON (/Users/contra/Projects/staeco/node_modules/knex-postgis/lib/functions.js:93:59)
    at onBoundary (seed.js:50:32)
    at /Users/contra/Projects/staeco/node_modules/async/dist/async.js:4637:20
    at replenish (/Users/contra/Projects/staeco/node_modules/async/dist/async.js:871:21)
    at /Users/contra/Projects/staeco/node_modules/async/dist/async.js:877:29
    at /Users/contra/Projects/staeco/node_modules/async/dist/async.js:840:20
    at onBoundary (seed.js:53:7)
    at /Users/contra/Projects/staeco/node_modules/async/dist/async.js:4637:20
    at replenish (/Users/contra/Projects/staeco/node_modules/async/dist/async.js:871:21)
    at /Users/contra/Projects/staeco/node_modules/async/dist/async.js:877:29
    at /Users/contra/Projects/staeco/node_modules/async/dist/async.js:840:20
```

Working with city boundaries.

**Comment by contra** [comment]
@tmcw Don't have the data on hand but it happened with a state in the US census TIGER data
